version: '3.8'

services:
  api:
    build: .
    container_name: finance-api-py
    ports:
      - "8888:8888"
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge
    external: true